/**
 * Extra England events — folk customs, parades, protests, festivals
 * Run with: npx tsx prisma/seed-extra.ts
 */
import { PrismaClient, EventType, EventStatus, IndoorOutdoor, SourceType } from "@prisma/client";

const prisma = new PrismaClient();

interface ExtraEvent {
  slug: string;
  title: string;
  type: EventType;
  status: EventStatus;
  region: string;
  county?: string;
  city?: string;
  venueName?: string;
  description: string;
  startDate: Date;
  endDate?: Date;
  startTime?: string;
  endTime?: string;
  allDay: boolean;
  recurringAnnual: boolean;
  free?: boolean;
  indoorOutdoor?: IndoorOutdoor;
  lat?: number;
  lng?: number;
  routeDescription?: string;
  nearestStation?: string;
  travelNotes?: string;
  tags: string[];
  featured: boolean;
  photoScore: number;
  bestViewingPosition?: string;
  lensSuggestion?: string;
  bestArrivalTime?: string;
  daytimeNightValue?: string;
  costumeCeremonial?: boolean;
  fireSmokeLight?: boolean;
  bannersFlagsCandles?: boolean;
  processionElements?: boolean;
  ritualSignificance?: boolean;
  protestVisibility?: boolean;
  routeMoving?: boolean;
  safetyNotes?: string;
  previousYearNotes?: string;
  officialUrl?: string;
  imageUrl?: string;
  crowdSizeEstimate?: string;
}

const Y = 2026;
const d = (m: number, day: number) =>
  new Date(`${Y}-${String(m).padStart(2, "0")}-${String(day).padStart(2, "0")}T12:00:00Z`);

const events: ExtraEvent[] = [

  // ── JANUARY ────────────────────────────────────────────────────────────────

  {
    slug: "haxey-hood-2026",
    title: "Haxey Hood",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "Yorkshire",
    county: "Lincolnshire",
    city: "Haxey",
    description: "One of England's oldest folk customs. Teams of hundreds of men attempt to push a leather tube (the Hood) to their chosen pub. The Fool is smoked, the Boggins run wild, and the village descends into joyful chaos that dates to the 14th century.",
    startDate: d(1, 6),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 53.5043, lng: -0.8086,
    tags: ["folk", "custom", "hood", "medieval", "crowd"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Village streets and the pub arrival points. Follow the Fool during the opening ceremony on the village green.",
    lensSuggestion: "24–70mm for crowd energy; 85mm to pick faces from the scrum",
    bestArrivalTime: "1pm for the opening ceremony before the scramble starts",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "The scrum is intense. Stay on the edges unless you want to be pulled in.",
    officialUrl: "https://haxeyhood.co.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Hood_Field_-_geograph.org.uk_-_313686.jpg",
    crowdSizeEstimate: "~500–1,000",
  },

  {
    slug: "whittlesea-straw-bear-2026",
    title: "Whittlesey Straw Bear Festival",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East of England",
    county: "Cambridgeshire",
    city: "Whittlesey",
    description: "A man completely encased in straw is paraded through town dancing at doorways to bring good luck. Accompanied by molly dancers, mummers, and morris sides. One of the most visually surreal folk customs in England.",
    startDate: d(1, 10),
    endDate: d(1, 11),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.5574, lng: -0.1272,
    tags: ["folk", "straw bear", "molly dancing", "mummers", "custom"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Market Place for the procession; doorways on the main street for close-up bear encounters",
    lensSuggestion: "35mm or 50mm prime for intimate street shots of the bear and dancers",
    bestArrivalTime: "10am Saturday for full day of street performance",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    previousYearNotes: "Very accessible — the bear walks right past you on narrow streets. Brilliant for portraiture.",
    officialUrl: "https://strawbear.org.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/78/Colourful_folk_in_Whittlesey_-_Whittlesea_Straw_Bear_Festival_2014_-_geograph.org.uk_-_3814377.jpg",
    crowdSizeEstimate: "~5,000",
  },

  // ── FEBRUARY ───────────────────────────────────────────────────────────────

  {
    slug: "atherstone-ball-game-2026",
    title: "Atherstone Ball Game",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "West Midlands",
    county: "Warwickshire",
    city: "Atherstone",
    description: "Played every Shrove Tuesday since the 12th century. A large ball is thrown from a window in Long Street and then fought over by hundreds of players for two hours. There are no rules, no teams, no referee — whoever holds the ball when the clock strikes 5pm wins.",
    startDate: d(2, 17),
    allDay: false,
    startTime: "15:00",
    endTime: "17:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.5775, lng: -1.5438,
    routeDescription: "Long Street, Atherstone — the entire length becomes the pitch",
    tags: ["folk", "ball game", "shrove tuesday", "custom", "medieval", "crowd"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Elevated positions on shop steps or window ledges above the crowd. The ball toss from the window at 3pm is the key shot.",
    lensSuggestion: "70–200mm from a safe elevated position; 35mm if you're brave enough to be in the crowd",
    bestArrivalTime: "2:30pm to secure a good elevated spot before the streets fill",
    daytimeNightValue: "daytime",
    costumeCeremonial: false,
    processionElements: false,
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "The scrum is serious — clothes get ripped. Stay elevated or on the edges unless prepared to be in it.",
    previousYearNotes: "The toss from the pub window draws a huge crowd. Get there early to stake out a high vantage point on Long Street.",
    officialUrl: "https://www.athherstoneballgame.co.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Atherstone_Ball_game_2012.jpg",
    crowdSizeEstimate: "~2,000–3,000",
  },

  {
    slug: "shrove-tuesday-football-ashbourne-2026",
    title: "Ashbourne Royal Shrovetide Football",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Derbyshire",
    city: "Ashbourne",
    description: "The world's oldest and most chaotic football match. Played across the entire town with goals 3 miles apart, hundreds of players, and almost no rules. The ball can go through houses, pubs, and rivers. Dating to at least the 12th century.",
    startDate: d(2, 17),
    endDate: d(2, 18),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 53.0170, lng: -1.7273,
    tags: ["folk", "football", "shrove tuesday", "custom", "crowd", "medieval"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Shaw Croft car park for the starting hug-up. The river crossing moments are spectacular but unpredictable.",
    lensSuggestion: "24–70mm — you'll need versatility as the game can move anywhere",
    bestArrivalTime: "1:30pm for the ball painting ceremony before the 2pm start",
    daytimeNightValue: "daytime",
    costumeCeremonial: false,
    processionElements: false,
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "The hug-up (scrum) is intense. River crossings are cold and chaotic. Waterproof your gear.",
    officialUrl: "https://www.ashbourneshrovetide.co.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Ashbourne_Royal_Shrovetide_Football_Goals%2C_old_and_new_-_geograph.org.uk_-_5311930.jpg",
    crowdSizeEstimate: "~5,000–8,000",
  },

  // ── MARCH ──────────────────────────────────────────────────────────────────

  {
    slug: "oxford-cambridge-boat-race-2026",
    title: "Oxford–Cambridge Boat Race",
    type: "SPORT",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "River Thames, Putney to Mortlake",
    description: "The annual University Boat Race draws hundreds of thousands to the Thames towpath. One of Britain's great sporting spectacles — the 4.2 mile race from Putney to Mortlake with crews of eight.",
    startDate: d(3, 29),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.4671, lng: -0.2165,
    routeDescription: "Putney Bridge to Chiswick Bridge — 4.2 miles along the Thames towpath",
    nearestStation: "Putney (overground), Hammersmith (tube)",
    tags: ["boat race", "rowing", "thames", "sport", "crowd"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Hammersmith Bridge for the bend; Barnes Bridge for a dramatic finish angle",
    lensSuggestion: "200–400mm for boats from the bank; 70–200mm at bridges",
    bestArrivalTime: "1pm to secure a towpath spot before crowds build",
    daytimeNightValue: "daytime",
    routeMoving: true,
    crowdSizeEstimate: "~250,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Oxford_winning_the_2022_Boat_Race_%28cropped%29.jpg",
  },

  {
    slug: "st-patricks-day-london-2026",
    title: "St Patrick's Day Parade, London",
    type: "PARADE",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Trafalgar Square",
    description: "One of the world's largest St Patrick's Day celebrations outside Ireland. The parade moves through central London to Trafalgar Square with Irish bands, dancers, floats, and thousands of green-clad revellers.",
    startDate: d(3, 15),
    allDay: false,
    startTime: "12:00",
    endTime: "18:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5080, lng: -0.1281,
    routeDescription: "Hyde Park Corner along Piccadilly to Trafalgar Square",
    nearestStation: "Charing Cross, Piccadilly Circus",
    tags: ["parade", "irish", "st patricks", "green", "trafalgar square"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Piccadilly for the parade; Trafalgar Square steps for the festival",
    lensSuggestion: "35–85mm for street portraits of revellers in costume",
    bestArrivalTime: "11:30am along the parade route at Piccadilly",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    routeMoving: true,
    bannersFlagsCandles: true,
    crowdSizeEstimate: "~100,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/London_Irish_Vintage_Club_in_the_St._Patrick%27s_Day_Parade_-_geograph.org.uk_-_4863140.jpg",
  },

  // ── APRIL ──────────────────────────────────────────────────────────────────

  {
    slug: "surrey-khalsa-day-vaisakhi-2026",
    title: "Surrey Khalsa Day — Vaisakhi Parade",
    type: "PARADE",
    status: "SCHEDULED",
    region: "South East",
    county: "Surrey",
    city: "Woking",
    description: "One of England's largest Vaisakhi celebrations outside London. The Nagar Kirtan (procession) moves through Woking with kirtan singers, gatka martial arts demonstrations, and thousands of participants in traditional dress. The procession ends at Woking's Shah Jahan Mosque — the first purpose-built mosque in England.",
    startDate: d(4, 12),
    allDay: false,
    startTime: "10:00",
    endTime: "16:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.3162, lng: -0.5595,
    routeDescription: "Nagar Kirtan procession through central Woking streets",
    nearestStation: "Woking",
    tags: ["vaisakhi", "sikh", "nagar kirtan", "gatka", "procession", "turban"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Along the procession route for the gatka performers and kirtan floats. The opening of the procession near the gurdwara is the most vibrant.",
    lensSuggestion: "85mm for portraits; 24–70mm for the gatka action",
    bestArrivalTime: "9:30am for the start of the procession",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    crowdSizeEstimate: "~10,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Vaisakhi_procession_in_Southall_-_geograph.org.uk_-_2360649.jpg",
  },

  {
    slug: "vaisakhi-trafalgar-square-2026",
    title: "Vaisakhi at Trafalgar Square",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Trafalgar Square",
    description: "London's official Vaisakhi celebration at Trafalgar Square. Sikh New Year festival with live bhangra, classical music, street food, and colourful traditional dress. One of the most visually vibrant events in London's annual calendar.",
    startDate: d(4, 11),
    allDay: false,
    startTime: "12:00",
    endTime: "18:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5080, lng: -0.1281,
    nearestStation: "Charing Cross",
    tags: ["vaisakhi", "sikh", "bhangra", "trafalgar square", "festival", "colour"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Trafalgar Square steps for elevated overview; ground level for crowd portraits",
    lensSuggestion: "50mm or 85mm for portraits of participants in traditional dress",
    bestArrivalTime: "12pm — the square fills quickly",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    bannersFlagsCandles: true,
    ritualSignificance: true,
    crowdSizeEstimate: "~30,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Sikh_festival_of_Vaisakhi%2C_Trafalgar_Square_-_geograph.org.uk_-_2476053.jpg",
  },

  {
    slug: "world-marbles-championship-2026",
    title: "World Marbles Championship",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "West Sussex",
    city: "Tinsley Green",
    venueName: "Greyhound Pub, Tinsley Green",
    description: "Held every Good Friday since 1588, the world's oldest marbles competition. Teams from around the world compete in the original ring at the Greyhound pub. Eccentric, brilliant, and completely photogenic.",
    startDate: d(4, 3),
    allDay: false,
    startTime: "10:30",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.1196, lng: -0.1742,
    nearestStation: "Gatwick Airport",
    tags: ["marbles", "custom", "world championship", "eccentric", "folk game"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Ringside — the marble ring is accessible to spectators",
    lensSuggestion: "Macro or 100mm for close-up shots of hands and marbles; 35mm for the crowd atmosphere",
    bestArrivalTime: "10am before the first games begin",
    daytimeNightValue: "daytime",
    ritualSignificance: true,
    costumeCeremonial: true,
    crowdSizeEstimate: "~200",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/2025_Chris_Pampel_in_play.jpg",
  },

  {
    slug: "hallaton-bottle-kicking-2026",
    title: "Hallaton Bottle Kicking & Hare Pie Scramble",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Leicestershire",
    city: "Hallaton",
    description: "Every Easter Monday, hare pie is scrambled for in the churchyard, then teams from Hallaton and neighbouring Medbourne play bottle kicking — a lawless inter-village game using small barrels of beer fought over across fields and streams.",
    startDate: d(4, 6),
    allDay: false,
    startTime: "14:30",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.5575, lng: -0.9286,
    tags: ["folk", "bottle kicking", "easter", "custom", "hare pie", "village game"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The hillside between the two villages for an overview of the cross-country game; the starting field for the initial chaos",
    lensSuggestion: "70–200mm for the scrum action across open ground",
    bestArrivalTime: "1pm for the hare pie scramble before the game starts",
    daytimeNightValue: "daytime",
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "Muddy fields. Wear boots. The game crosses streams.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Hallaton_bottle_kicking_-_geograph.org.uk_-_441676.jpg",
    crowdSizeEstimate: "~1,000–2,000",
  },

  {
    slug: "whitby-goth-weekend-april-2026",
    title: "Whitby Goth Weekend (April)",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "Yorkshire",
    county: "North Yorkshire",
    city: "Whitby",
    description: "Twice-yearly gathering of the global goth community in Bram Stoker's Dracula town. Thousands of elaborately costumed goths descend on Whitby for music, markets, and promenading. Against the backdrop of Whitby Abbey ruins — one of the most photogenic events in England.",
    startDate: d(4, 24),
    endDate: d(4, 26),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "BOTH",
    lat: 54.4858, lng: -0.6206,
    nearestStation: "Whitby",
    tags: ["goth", "costume", "dracula", "whitby", "subculture", "abbey"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Whitby Abbey graveyard steps for portraits against the abbey ruins; the harbour front for the promenade; the swing bridge for arriving groups",
    lensSuggestion: "85mm f/1.4 or 50mm f/1.8 for moody portraits; wide angle for the abbey backdrop",
    bestArrivalTime: "Late afternoon Saturday for the main promenade to the abbey",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    previousYearNotes: "Golden hour on Saturday at the abbey steps is unmissable. Goths are generally very happy to pose.",
    crowdSizeEstimate: "~15,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/History_Of_Guns_-_Del_Alien_-_Whitby_Goth_Weekend_April_2006.jpg",
  },

  {
    slug: "london-marathon-2026",
    title: "London Marathon",
    type: "SPORT",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    description: "One of the world's great marathons — 50,000 runners and hundreds of thousands of spectators. The costume runners alone make for extraordinary photography, plus the elite finish and the emotional scenes at Mile 24.",
    startDate: d(4, 26),
    allDay: false,
    startTime: "09:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5074, lng: -0.1278,
    routeDescription: "Blackheath/Greenwich → Tower Bridge → Embankment → The Mall",
    nearestStation: "Blackheath (start); Tower Hill, Embankment, Westminster, St James's Park",
    tags: ["marathon", "running", "costume", "london", "sport", "crowd"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Tower Bridge for the iconic split-level shot; Mile 24 on Embankment for the emotional struggle; The Mall finish for elite athletes",
    lensSuggestion: "70–200mm at Tower Bridge; 24–70mm at the finish",
    bestArrivalTime: "9:30am at Tower Bridge for the elite women; 11am for the costume runners",
    daytimeNightValue: "daytime",
    routeMoving: true,
    bannersFlagsCandles: true,
    officialUrl: "https://www.londonmarathon.com/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/2021_London_Marathon.jpg",
    crowdSizeEstimate: "~750,000 spectators (50,000 runners)",
  },

  // ── MAY ────────────────────────────────────────────────────────────────────

  {
    slug: "padstow-obby-oss-2026",
    title: "Padstow Obby Oss",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Cornwall",
    city: "Padstow",
    description: "May Day morning in Padstow erupts from midnight with singing through the streets. Two Obby Osses (ritual hobby horses) process through the town trying to capture women under their skirts for luck. The entire town wears blue and white ribbons and dances through narrow streets in one of England's most ancient and euphoric customs.",
    startDate: d(5, 1),
    allDay: false,
    startTime: "00:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.5384, lng: -4.9374,
    tags: ["obby oss", "hobby horse", "may day", "cornwall", "folk", "custom", "ancient"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The main harbour square at midnight for the start; narrow lanes for the procession intimacy; Market Place for the dancing",
    lensSuggestion: "35mm or 50mm prime, high ISO (3200+) for midnight start; f/1.8 minimum",
    bestArrivalTime: "11:30pm 30 April for the midnight singing start, or 9am May 1 for the daytime procession",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    safetyNotes: "Town gets extremely crowded. Book accommodation many months in advance.",
    previousYearNotes: "The narrow streets at night with torch light and singing are extraordinary. Day is more accessible but night has the magic.",
    officialUrl: "https://www.padstowmayday.com/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Red_obby_oss_maiden_20050502.jpg",
    crowdSizeEstimate: "~5,000",
  },

  {
    slug: "helston-flora-day-2026",
    title: "Helston Flora Day",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Cornwall",
    city: "Helston",
    description: "Every 8 May, Helston celebrates the arrival of spring with the Furry Dance — couples in formal dress dance through the streets and through private houses, in and out of shops and gardens. One of England's most distinctive and joyful folk customs.",
    startDate: d(5, 8),
    allDay: false,
    startTime: "07:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.1009, lng: -5.2744,
    tags: ["furry dance", "flora day", "cornwall", "folk", "custom", "formal dress"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Coinagehall Street for the main midday dance; anywhere on the route where dancers pass through houses",
    lensSuggestion: "50mm for the elegant formal-dress procession; 85mm for portraits",
    bestArrivalTime: "7am for the children's early dance; midday dance is the most spectacular",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    previousYearNotes: "The formal morning dress against the slate Cornish streets creates a uniquely English surreal image.",
    officialUrl: "https://www.helstonflora.org.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Leading_the_mid-day_dance_on_Helston_Flora_Day_2016_-_geograph.org.uk_-_4951491.jpg",
    crowdSizeEstimate: "~10,000",
  },

  {
    slug: "coopers-hill-cheese-rolling-2026",
    title: "Cooper's Hill Cheese-Rolling",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Gloucestershire",
    city: "Brockworth",
    venueName: "Cooper's Hill, Brockworth",
    description: "Every Spring Bank Holiday Monday, competitors hurl themselves down a near-vertical hill chasing a 7lb Double Gloucester cheese. Racers tumble, cartwheel and crash down the 1:2 gradient while St John Ambulance crews stand ready. One of the most absurd and brilliant folk customs in England.",
    startDate: d(5, 25),
    allDay: false,
    startTime: "12:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.8540, lng: -2.1470,
    travelNotes: "No parking near the hill — use park and ride from Cheltenham or walk from Brockworth village",
    tags: ["cheese rolling", "gloucester", "folk custom", "hill race", "eccentric", "british"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Hillside spectator area at the top for the launch moment; bottom of the hill for the crash arrivals — the catchers and ambulance crews add drama",
    lensSuggestion: "200–400mm from the top looking down to compress the descent; 70–200mm at the bottom for impact shots",
    bestArrivalTime: "10am — access is on foot and the hill fills fast",
    daytimeNightValue: "daytime",
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "The spectator hillside is steep and slippery. The bottom of the hill is dangerous from falling competitors. The event is unofficial — follow safety cordons.",
    previousYearNotes: "Telephoto from the upper spectator bank gives the best compression of the descent. Bottom of hill gives chaotic energy but requires fast reflexes.",
    officialUrl: "https://www.cheese-rolling.co.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/A_view_down_Cooper%27s_Hill.jpg",
    crowdSizeEstimate: "~5,000",
  },

  {
    slug: "jack-in-the-green-hastings-2026",
    title: "Jack in the Green, Hastings",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "East Sussex",
    city: "Hastings",
    description: "Every May Day Bank Holiday, a 10-foot tall figure covered entirely in greenery leads a procession through Hastings with hundreds of morris dancers, bogeys, and faces painted green. The procession climbs to the castle where Jack is 'slain' to release the spirit of summer.",
    startDate: d(5, 4),
    endDate: d(5, 5),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.8549, lng: 0.5736,
    tags: ["jack in the green", "may day", "folk", "morris", "hastings", "green man", "custom"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The seafront for the procession; Hastings Old Town streets for the intimate dancing; castle ruins for the ceremonial killing",
    lensSuggestion: "35mm for the packed streets; 85mm for portraits of painted faces and Jack himself",
    bestArrivalTime: "10am Monday for the morning procession assembly",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    fireSmokeLight: true,
    crowdSizeEstimate: "~10,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Jack_in_the_Green_Procession_at_Hastings_May_Day_Celebration_2023_%28142%29.jpg",
  },

  {
    slug: "woolsack-race-tetbury-2026",
    title: "Woolsack Race, Tetbury",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Gloucestershire",
    city: "Tetbury",
    description: "Every Whit Bank Holiday Monday, competitors race up and down Gumstool Hill carrying 60lb woolsacks (35lb for women). Dating to the 17th century when drovers showed off their strength at the wool market. Pubs at both ends of the course ensure good cheer.",
    startDate: d(5, 25),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.6382, lng: -2.1619,
    tags: ["woolsack", "tetbury", "folk", "custom", "race", "gloucestershire"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Halfway up Gumstool Hill for the faces of effort and pain",
    lensSuggestion: "70–200mm to compress the hill gradient",
    bestArrivalTime: "1pm for good spots along the course",
    daytimeNightValue: "daytime",
    routeMoving: true,
    ritualSignificance: true,
    crowdSizeEstimate: "~2,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Gumstool_Hill_Tetbury_-_geograph.org.uk_-_274671.jpg",
  },

  {
    slug: "chelsea-flower-show-2026",
    title: "RHS Chelsea Flower Show",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Royal Hospital Chelsea",
    description: "The world's most prestigious flower show. Five days of extraordinary gardens, floral displays, and horticultural theatre in the grounds of the Royal Hospital Chelsea. Attracts royalty, celebrities, and 150,000 visitors.",
    startDate: d(5, 19),
    endDate: d(5, 23),
    allDay: false,
    startTime: "08:00",
    endTime: "20:00",
    recurringAnnual: true,
    free: false,
    indoorOutdoor: "OUTDOOR",
    lat: 51.4875, lng: -0.1567,
    nearestStation: "Sloane Square",
    tags: ["chelsea", "flowers", "gardens", "royal", "show", "horticulture"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Show gardens for the full designer spaces; Great Pavilion interior for macro flower shots",
    lensSuggestion: "90mm macro for flower detail; 24–70mm for the garden set pieces",
    bestArrivalTime: "Opening at 8am for fewer crowds and better light in the gardens",
    daytimeNightValue: "daytime",
    crowdSizeEstimate: "~150,000 over 5 days",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Main_pavillion_at_RHS_Chelsea_Flower_Show_2009.jpg",
  },

  {
    slug: "grovely-rights-day-2026",
    title: "Grovely Rights Day",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Wiltshire",
    city: "Great Wishford",
    description: "Every 29 May (Oak Apple Day), villagers walk to Grovely Wood at dawn, cut green branches, and march to Salisbury Cathedral to claim their ancient forest rights by shouting 'Grovely! Grovely! Grovely! And all Grovely!' — a right won in 1603 and still vigorously defended.",
    startDate: d(5, 29),
    allDay: false,
    startTime: "06:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.1006, lng: -1.8798,
    tags: ["oak apple day", "custom", "ancient rights", "wiltshire", "folk", "dawn"],
    featured: true,
    photoScore: 4,
    bestViewingPosition: "The cathedral close in Salisbury for the rights proclamation; the woodland at dawn for the branch cutting",
    lensSuggestion: "35mm prime at dawn in low light (ISO 3200+); 24mm for the cathedral facade",
    bestArrivalTime: "5:30am for the dawn woodland walk — this is a proper before-sunrise start",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    bannersFlagsCandles: true,
    ritualSignificance: true,
    routeMoving: true,
    crowdSizeEstimate: "~200",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9e/GrovelyWoods1.JPG",
  },

  // ── JUNE ───────────────────────────────────────────────────────────────────

  {
    slug: "trooping-the-colour-2026",
    title: "Trooping the Colour",
    type: "ROYAL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Horse Guards Parade / The Mall",
    description: "The monarch's official birthday parade. Hundreds of troops in full ceremonial dress, massed bands, royal procession down The Mall, and the RAF flypast from Buckingham Palace balcony. One of the great set-piece spectacles in the royal calendar.",
    startDate: d(6, 13),
    allDay: false,
    startTime: "10:00",
    endTime: "13:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5041, lng: -0.1281,
    routeDescription: "Buckingham Palace → The Mall → Horse Guards Parade → return via The Mall",
    nearestStation: "St James's Park, Charing Cross",
    tags: ["trooping", "royal", "ceremony", "guards", "military", "horse", "bearskin"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The Mall for the royal procession; Horseguards Road for the parade ground action; Birdcage Walk for the return",
    lensSuggestion: "200–400mm for the guards at distance; 70–200mm on The Mall for the procession",
    bestArrivalTime: "8am to secure a spot on The Mall before barriers fill",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    previousYearNotes: "The Mall gives the iconic shot of guards against the Buckingham Palace backdrop. Horseguards Arch is good but requires a viewing ticket.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Trooping_the_Colour_2018_%2813%29.jpg",
    crowdSizeEstimate: "~100,000",
  },

  {
    slug: "royal-ascot-2026",
    title: "Royal Ascot",
    type: "SPORT",
    status: "SCHEDULED",
    region: "South East",
    county: "Berkshire",
    city: "Ascot",
    venueName: "Ascot Racecourse",
    description: "Five days of flat racing and extraordinary fashion. The Royal Procession along the track opens each day. The Ascot hats, the morning dress, and the Silver Ring crowds create one of England's greatest fashion spectacles alongside elite horse racing.",
    startDate: d(6, 16),
    endDate: d(6, 20),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: false,
    indoorOutdoor: "OUTDOOR",
    lat: 51.4079, lng: -0.6677,
    nearestStation: "Ascot",
    tags: ["royal ascot", "racing", "hats", "fashion", "royal", "horse"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Silver Ring (public enclosure) for the hat parade and race atmosphere; trackside for the horses",
    lensSuggestion: "85–200mm for portrait-style hat shots; 400mm for trackside racing",
    bestArrivalTime: "1pm before the Royal Procession at 2pm",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    routeMoving: true,
    crowdSizeEstimate: "~300,000 over 5 days",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Ascot_23062023_2048x1536.jpg",
  },

  {
    slug: "appleby-horse-fair-2026",
    title: "Appleby Horse Fair",
    type: "FAIR",
    status: "SCHEDULED",
    region: "North West",
    county: "Cumbria",
    city: "Appleby-in-Westmorland",
    description: "Europe's largest gathering of Gypsies and Travellers. Horses are washed and raced through the River Eden, traditional vardos (wagons) line the lanes, and the Fair Hill site becomes a vast temporary city. One of the most photogenic and culturally significant events in England.",
    startDate: d(6, 4),
    endDate: d(6, 9),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.5790, lng: -2.4886,
    nearestStation: "Appleby",
    tags: ["gypsy", "traveller", "horse", "fair", "romany", "river washing", "vardo"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The Sands (riverside) for horse washing in the Eden; Fair Hill for the wagons and horse dealing; the main road for the trotting",
    lensSuggestion: "35mm for the river scenes; 85mm for portraits; 200mm for the horse trotting",
    bestArrivalTime: "Morning for the river washing when light is best",
    daytimeNightValue: "daytime",
    costumeCeremonial: false,
    routeMoving: true,
    safetyNotes: "Be respectful of privacy — ask before photographing children and wagons. The community is generally welcoming of respectful documentary photographers.",
    previousYearNotes: "The river washing is the definitive shot — horses up to their chests in water with handlers in smart dress.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Appleby_Horse_Fair_-_geograph.org.uk_-_5877759.jpg",
    crowdSizeEstimate: "~30,000–50,000",
  },

  {
    slug: "pride-london-2026",
    title: "Pride in London",
    type: "PARADE",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    description: "One of the world's largest Pride events. A million people line the route through central London as the parade of floats, community groups, and activists passes from Marble Arch to Whitehall. Followed by festival stages across the West End.",
    startDate: d(6, 27),
    allDay: false,
    startTime: "12:00",
    endTime: "21:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5100, lng: -0.1355,
    routeDescription: "Marble Arch → Oxford Street → Regent Street → Piccadilly → Whitehall",
    nearestStation: "Marble Arch, Oxford Circus, Piccadilly Circus",
    tags: ["pride", "lgbtq", "parade", "rainbow", "protest", "celebration", "london"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Regent Street for colour and scale; Trafalgar Square for the post-parade gathering; Soho for the neighbourhood celebrations",
    lensSuggestion: "35mm or 50mm for street portraits; wide angle for the scale on Regent Street",
    bestArrivalTime: "11am to secure a spot on Regent Street before the parade route fills",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    protestVisibility: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Pride_London_2019_%2848394464606%29.jpg",
    crowdSizeEstimate: "~1 million",
  },

  // ── JULY ───────────────────────────────────────────────────────────────────

  {
    slug: "swan-upping-2026",
    title: "Swan Upping",
    type: "ROYAL",
    status: "SCHEDULED",
    region: "South East",
    county: "Berkshire",
    city: "Henley-on-Thames",
    description: "The ancient annual census of mute swans on the Thames. Skiffs bearing the flags of the Crown and the Worshipful Companies of Vintners and Dyers row from Sunbury to Abingdon. Swan Uppers in red uniforms stand to attention, calling 'All up!' as cygnets are caught and marked.",
    startDate: d(7, 20),
    endDate: d(7, 24),
    allDay: false,
    startTime: "09:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5352, lng: -0.9979,
    routeDescription: "Thames from Sunbury Lock to Abingdon Bridge over 5 days",
    tags: ["swan upping", "royal", "thames", "historic", "ceremony", "river"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Lock keeper's cottage gardens along the Thames; riverside pubs on the route; bridges for elevated angles as skiffs pass beneath",
    lensSuggestion: "200–400mm for close-ups of the skiffs and swan handling from the bank",
    bestArrivalTime: "Check the route schedule — the flotilla passes each location at a specific time",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    routeMoving: true,
    ritualSignificance: true,
    previousYearNotes: "The red uniforms against the river and summer trees are classically English. Bridge shots with reflections work beautifully.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/43/Swan_upping_at_Henley.jpg",
    crowdSizeEstimate: "~200–500 (riverside)",
  },

  {
    slug: "doggetts-coat-and-badge-2026",
    title: "Doggett's Coat and Badge Race",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "River Thames",
    description: "The oldest continuous rowing race in the world (since 1715). Six young Thames watermen race 4.5 miles from London Bridge to Chelsea against the tide. The winner receives a scarlet coat with a large silver badge depicting the Hanoverian horse.",
    startDate: d(7, 1),
    allDay: false,
    startTime: "11:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5055, lng: -0.0900,
    routeDescription: "London Bridge to Chelsea Bridge — 4.5 miles upstream against the tide",
    nearestStation: "London Bridge",
    tags: ["rowing", "thames", "watermen", "historic", "oldest race", "royal"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Any Thames bridge on the route; Chelsea Embankment for the finish",
    lensSuggestion: "200–400mm for the rowers from bridges",
    bestArrivalTime: "10:30am at London Bridge for the start",
    daytimeNightValue: "daytime",
    routeMoving: true,
    ritualSignificance: true,
    costumeCeremonial: true,
    crowdSizeEstimate: "~500",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Doggett%27s_Coat_and_Badge_winners_c1901_Stone.jpg",
  },

  // ── AUGUST ─────────────────────────────────────────────────────────────────

  {
    slug: "notting-hill-carnival-2026",
    title: "Notting Hill Carnival",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Notting Hill / Ladbroke Grove",
    description: "Europe's largest street festival. Two million people over two days. Sound systems, soca, calypso, steel pan, and the grand carnival procession of elaborate masquerade costumes. The Monday Grand Parade is the photographic highlight — thousands of costumed performers, massive sound trucks, and wall-to-wall colour.",
    startDate: d(8, 23),
    endDate: d(8, 24),
    allDay: false,
    startTime: "09:00",
    endTime: "21:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5152, lng: -0.2050,
    nearestStation: "Ladbroke Grove, Notting Hill Gate, Westbourne Park",
    tags: ["carnival", "notting hill", "caribbean", "costume", "soca", "parade", "colour", "mas"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Ladbroke Grove for the parade with depth; Portobello Road junction for the sound systems; Kensington Park Road for the masquerade close-ups",
    lensSuggestion: "35mm or 50mm prime — you'll be in very tight crowds. Fast lens (f/1.8) for the shaded streets",
    bestArrivalTime: "10am Monday (Grand Parade day) to establish a position before crowds make movement impossible",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    safetyNotes: "Very crowded — keep bags zipped. Phone pickpocketing is common. Stay aware of your surroundings especially near sound systems.",
    previousYearNotes: "The masquerade costumes on Monday are extraordinary — feathers, sequins, and 6-foot headdresses. Get close on Kensington Park Road before the route fills at midday.",
    officialUrl: "https://nhcarnival.org/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Notting_Hill_Carnival_2018_%283%29.jpg",
    crowdSizeEstimate: "~2 million over 2 days",
  },

  {
    slug: "manchester-pride-2026",
    title: "Manchester Pride Festival",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "North West",
    county: "Greater Manchester",
    city: "Manchester",
    description: "One of the UK's biggest Pride festivals over the August bank holiday weekend. The parade through the city centre on Saturday is followed by four days of music and celebration in the Gay Village. Massive outdoor stages, community floats, and hundreds of thousands of revellers.",
    startDate: d(8, 21),
    endDate: d(8, 24),
    allDay: true,
    recurringAnnual: true,
    free: false,
    indoorOutdoor: "OUTDOOR",
    lat: 53.4772, lng: -2.2321,
    nearestStation: "Manchester Piccadilly, Deansgate",
    tags: ["pride", "manchester", "lgbtq", "parade", "rainbow", "festival", "gay village"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Deansgate for the parade; Canal Street for the Village atmosphere",
    lensSuggestion: "35mm prime for street portraits; 24mm for the crowd scale",
    bestArrivalTime: "11am Saturday for the parade assembly",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    routeMoving: true,
    bannersFlagsCandles: true,
    crowdSizeEstimate: "~200,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Manchester_Pride_2012_Procession_-_geograph.org.uk_-_3100164.jpg",
  },

  // ── SEPTEMBER ──────────────────────────────────────────────────────────────

  {
    slug: "abbots-bromley-horn-dance-2026",
    title: "Abbots Bromley Horn Dance",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "West Midlands",
    county: "Staffordshire",
    city: "Abbots Bromley",
    description: "On Wakes Monday (first Monday after 4 September), six men carrying 1,000-year-old reindeer antlers perform an ancient processional dance around the farms and fields of Abbots Bromley. Accompanied by a hobby horse, Maid Marian, a bowman, a jester, and a triangle player. The horns are kept in the church and collected at 8am.",
    startDate: d(9, 7),
    allDay: false,
    startTime: "08:00",
    endTime: "20:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.8207, lng: -1.8730,
    tags: ["horn dance", "abbots bromley", "folk", "custom", "ancient", "deer antlers", "staffordshire"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The village green for the 8am horn collection; the rural farm visits throughout the day for isolated shots against countryside; the final return at dusk",
    lensSuggestion: "85mm for portraits of horn dancers; 35mm for the village green scenes; 200mm for the rural landscape shots",
    bestArrivalTime: "7:45am for the horn collection ceremony from the church",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    previousYearNotes: "The deer antlers against the English countryside at golden hour are extraordinary. Follow the group through the day — they cover many miles visiting farms.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Horn_Dance%2C_Blithfield_Reservoir_-_2006-09-11.jpg",
    crowdSizeEstimate: "~1,000–2,000",
  },

  {
    slug: "great-north-run-2026",
    title: "Great North Run",
    type: "SPORT",
    status: "SCHEDULED",
    region: "North East",
    city: "Newcastle upon Tyne",
    description: "The world's largest half marathon — 57,000 runners from Newcastle to South Shields. The Red Arrows flypast, the Tyne Bridge start, and the sea finish create multiple iconic photography opportunities.",
    startDate: d(9, 6),
    allDay: false,
    startTime: "10:30",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.9783, lng: -1.6174,
    routeDescription: "Newcastle City Centre → Tyne Bridge → Gateshead → South Shields seafront",
    nearestStation: "Newcastle Central",
    tags: ["great north run", "half marathon", "running", "newcastle", "sport", "tyne bridge"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Tyne Bridge for the massed start and Red Arrows; Gateshead for the mid-race crowd; South Shields seafront for the emotional finish",
    lensSuggestion: "70–200mm at the Tyne Bridge; 24–70mm at the finish",
    bestArrivalTime: "9:30am at the Tyne Bridge for the Red Arrows before the 10:30am start",
    daytimeNightValue: "daytime",
    routeMoving: true,
    crowdSizeEstimate: "~500,000 spectators (57,000 runners)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Meseret_Defar%2C_Great_North_Run_-_geograph.org.uk_-_3656060.jpg",
  },

  // ── OCTOBER ────────────────────────────────────────────────────────────────

  {
    slug: "ottery-st-mary-tar-barrels-2026",
    title: "Ottery St Mary Tar Barrel Rolling",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Devon",
    city: "Ottery St Mary",
    description: "Every 5 November, men, women, and children carry flaming tar barrels on their backs through the crowded streets of Ottery St Mary. Not health and safety approved. Absolutely extraordinary. The largest barrel is saved for midnight.",
    startDate: d(11, 5),
    allDay: false,
    startTime: "17:00",
    endTime: "00:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.7466, lng: -3.2820,
    tags: ["tar barrels", "fire", "devon", "bonfire night", "folk custom", "dangerous", "night"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Any point on the main street circuit — barrels pass regularly. The Square for multiple barrel encounters. The midnight finale is the largest barrel.",
    lensSuggestion: "f/2.8 or wider, ISO 3200–6400. 35mm prime. The fire provides dramatic but uneven light.",
    bestArrivalTime: "5pm for the children's barrels — equally dramatic and more accessible",
    daytimeNightValue: "night",
    fireSmokeLight: true,
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "Stand back — the barrels are genuinely on fire. Burning embers fall into the crowd. Wear nothing precious. The crowd presses in close.",
    previousYearNotes: "Slow shutter (1/15s) to blur the fire trails across the frame. Manual exposure. The barrel carriers' faces lit by flame are extraordinary portraits.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Ottery_St_Mary_%2C_Tar_Barrels_-_geograph.org.uk_-_5190339.jpg",
    crowdSizeEstimate: "~8,000",
  },

  {
    slug: "diwali-trafalgar-square-2026",
    title: "Diwali on the Square",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Trafalgar Square",
    description: "London's official Diwali celebration in Trafalgar Square. Dance performances, rangoli art, Indian food, lanterns, and a light show on the National Gallery. Tens of thousands attend what is one of London's most colourful and atmospheric free events.",
    startDate: d(10, 17),
    allDay: false,
    startTime: "12:00",
    endTime: "21:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5080, lng: -0.1281,
    nearestStation: "Charing Cross",
    tags: ["diwali", "festival of lights", "trafalgar square", "rangoli", "lanterns", "dances"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Trafalgar Square steps for overview; ground level for the rangoli and dancers; the square at dusk for the light show against the National Gallery",
    lensSuggestion: "35mm for the crowd and colour; 85mm for dancer portraits; long exposure (tripod) for the evening light show",
    bestArrivalTime: "3pm for the performances; stay for dusk when the light show begins",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    bannersFlagsCandles: true,
    fireSmokeLight: true,
    ritualSignificance: true,
    previousYearNotes: "The transition from daytime colour to the evening lights is the money shot. Stay until at least 6pm.",
    crowdSizeEstimate: "~50,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Prime_Minister_Keir_Starmer_hosts_Diwali_Reception_%2854103309048%29.jpg",
  },

  {
    slug: "nottingham-goose-fair-2026",
    title: "Nottingham Goose Fair",
    type: "FAIR",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Nottinghamshire",
    city: "Nottingham",
    venueName: "Forest Recreation Ground",
    description: "One of Europe's largest and oldest travelling fairs — established in the 13th century. The lights of 500+ rides and stalls, the noise, the candy floss, the ghost trains. Brilliant night photography of the spinning fairground in full swing.",
    startDate: d(10, 7),
    endDate: d(10, 11),
    allDay: false,
    startTime: "12:00",
    endTime: "22:30",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.9710, lng: -1.1645,
    nearestStation: "Nottingham",
    tags: ["fairground", "fair", "goose fair", "rides", "lights", "night photography"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Any elevated vantage point for long exposure of the spinning rides; ground level for the faces of riders",
    lensSuggestion: "Wide angle (16–35mm) for long exposure rides at night; 50mm for stall portraits",
    bestArrivalTime: "Dusk — 6–8pm for the rides lit against a darkening sky",
    daytimeNightValue: "night",
    fireSmokeLight: true,
    crowdSizeEstimate: "~400,000 over 5 days",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Nottingham_Goose_Fair.JPG",
  },

  {
    slug: "whitby-goth-weekend-october-2026",
    title: "Whitby Goth Weekend (October)",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "Yorkshire",
    county: "North Yorkshire",
    city: "Whitby",
    description: "The larger of the two annual Whitby Goth Weekends — the October event attracts more attendees and often has more elaborate costumes. The combination of Halloween timing, the abbey ruins, and the Victorian fishing town creates the ultimate goth backdrop.",
    startDate: d(10, 23),
    endDate: d(10, 25),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "BOTH",
    lat: 54.4858, lng: -0.6206,
    nearestStation: "Whitby",
    tags: ["goth", "costume", "dracula", "whitby", "subculture", "abbey", "halloween"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Whitby Abbey graveyard for portraits; the 199 steps for the procession effect; harbour front at golden hour for silhouettes",
    lensSuggestion: "85mm f/1.4 for moody low-light portraits against the abbey; 35mm for the streets",
    bestArrivalTime: "3pm Saturday for the peak promenade; stay for sunset at the abbey",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    fireSmokeLight: false,
    previousYearNotes: "October has the best costumes and autumn light. The 199 steps at sunset with costumed goths is one of England's great photographic moments.",
    officialUrl: "https://whitbygothweekend.co.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Whitby_Goth_Weekend_%284550697933%29.jpg",
    crowdSizeEstimate: "~20,000",
  },

  // ── NOVEMBER ───────────────────────────────────────────────────────────────

  {
    slug: "lewes-bonfire-night-2026",
    title: "Lewes Bonfire Night",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "South East",
    county: "East Sussex",
    city: "Lewes",
    description: "England's most spectacular Bonfire Night. Six bonfire societies process through the town with flaming crosses, Viking longboats, and effigies. Thousands of torchbearers, 17 bonfires, and fireworks over the castle. The societies wear period costume — including Zulu warriors, smugglers, and convicts.",
    startDate: d(11, 5),
    allDay: false,
    startTime: "18:00",
    endTime: "23:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.8743, lng: 0.0117,
    nearestStation: "Lewes",
    tags: ["bonfire night", "lewes", "procession", "fire", "torch", "effigies", "costume"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The High Street for the main procession of all six societies; individual bonfire sites for the ceremony and fireworks",
    lensSuggestion: "f/2.8 or wider at ISO 3200–6400; 35mm or 50mm prime. Long exposure (2–4s) for torch trails.",
    bestArrivalTime: "5pm to be in place before the streets close — road closures from 5:30pm",
    daytimeNightValue: "night",
    costumeCeremonial: true,
    fireSmokeLight: true,
    processionElements: true,
    bannersFlagsCandles: true,
    ritualSignificance: true,
    routeMoving: true,
    safetyNotes: "Bangers are thrown into the crowd. Wear clothes you don't mind scorching. Be alert to burning debris. Very crowded — plan your exit route in advance.",
    previousYearNotes: "The flaming cross procession is the defining image. Slow shutter to blur torch movement. The town gets extremely crowded after 7pm — position yourself early.",
    officialUrl: "https://lewesbonfirecouncil.org.uk/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Lewes_Bonfire%2C_Lewes_Borough_Bonfire_Society.jpg",
    crowdSizeEstimate: "~80,000",
  },

  {
    slug: "lords-mayors-show-2026",
    title: "Lord Mayor's Show",
    type: "PARADE",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "City of London",
    description: "The Lord Mayor of London's inaugural procession through the City — one of the world's oldest annual civic parades dating to 1215. More than 7,000 participants, 200 horses, military bands, floats, and the Lord Mayor's State Coach.",
    startDate: d(11, 14),
    allDay: false,
    startTime: "11:00",
    endTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5155, lng: -0.0922,
    routeDescription: "Mansion House → Bank → St Paul's → Aldwych → Royal Courts of Justice → return",
    nearestStation: "Bank, St Paul's, Blackfriars",
    tags: ["lord mayor", "parade", "city of london", "historic", "coach", "ceremonial"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Mansion House for the departure; Ludgate Hill for St Paul's Cathedral backdrop; the Embankment for the riverside fireworks at dusk",
    lensSuggestion: "70–200mm for the coaches; 24–70mm on Ludgate Hill for the cathedral framing",
    bestArrivalTime: "10am at Mansion House for the best parade positions",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    fireSmokeLight: true,
    officialUrl: "https://www.lordmayorsshow.london/",
    crowdSizeEstimate: "~500,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Lord_Mayor%27s_Show_2016_%2830638803490%29.jpg",
  },

  {
    slug: "remembrance-cenotaph-2026",
    title: "Remembrance Sunday — Cenotaph",
    type: "VIGIL",
    status: "SCHEDULED",
    region: "London",
    city: "London",
    venueName: "Cenotaph, Whitehall",
    description: "The national act of remembrance at the Cenotaph in Whitehall. The two-minute silence, the royals and senior politicians laying wreaths, and the march past of veterans. One of the most solemn and visually powerful annual events in England.",
    startDate: d(11, 8),
    allDay: false,
    startTime: "10:30",
    endTime: "13:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5025, lng: -0.1283,
    nearestStation: "Westminster, Charing Cross",
    tags: ["remembrance", "cenotaph", "veterans", "silence", "poppies", "military", "solemn"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Press positions are restricted, but Whitehall behind barriers gives good angles. The march past of veterans in the afternoon is more accessible.",
    lensSuggestion: "200–400mm for the wreath laying from distance; 85mm for veteran portraits during the march",
    bestArrivalTime: "9am to secure a viewing position on Whitehall before barriers fill",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    ritualSignificance: true,
    routeMoving: true,
    previousYearNotes: "The veterans' march in the afternoon is the most accessible and emotionally rich photography opportunity. Medals, berets, and poppy wreaths.",
    crowdSizeEstimate: "~15,000 (ceremony area)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/Prime_Minister_Keir_Starmer_-_Remembrance_Sunday_at_the_Cenotaph_-_54910979647.jpg",
  },

  {
    slug: "burning-of-the-clocks-brighton-2026",
    title: "Burning of the Clocks, Brighton",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "South East",
    county: "East Sussex",
    city: "Brighton",
    description: "Brighton's winter solstice parade. Hundreds of lantern-makers carry their handmade paper and willow clocks through the city to the beach, where they are burned on a bonfire with fireworks. A community-made spectacle of extraordinary beauty.",
    startDate: d(12, 21),
    allDay: false,
    startTime: "17:00",
    endTime: "21:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 50.8229, lng: -0.1363,
    nearestStation: "Brighton",
    tags: ["lanterns", "solstice", "brighton", "fire", "parade", "winter", "beach bonfire"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The procession route through Brighton streets for lanterns against dark sky; the beach bonfire site for the burning finale",
    lensSuggestion: "f/2.8, ISO 3200–6400 for the lantern procession; long exposure at the bonfire",
    bestArrivalTime: "4:30pm to see the procession assembly before dark",
    daytimeNightValue: "night",
    fireSmokeLight: true,
    processionElements: true,
    bannersFlagsCandles: true,
    ritualSignificance: true,
    routeMoving: true,
    previousYearNotes: "The paper clock lanterns glow beautifully in the dark streets. Slow sync flash or purely ambient at ISO 3200. The beach bonfire reflects in the sea.",
    officialUrl: "https://www.burningoftheclocks.co.uk/",
    crowdSizeEstimate: "~20,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Burning_the_Clocks%2C_Brighton_%285284087150%29.jpg",
  },

  // ── NEW ADDITIONS ───────────────────────────────────────────────────────────

  {
    slug: "hocktide-hungerford-2026",
    title: "Hocktide, Hungerford",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "Berkshire",
    city: "Hungerford",
    description: "One of England's most eccentric civic ceremonies. On the second Tuesday after Easter, Tutti-men in top hats with flower-topped poles tour every property in Hungerford demanding tribute: a penny from men, a kiss from women. The day begins with the blowing of a hunting horn from the Town Hall balcony, followed by a court luncheon where oranges are thrown to the crowd.",
    startDate: d(4, 14),
    allDay: false,
    startTime: "09:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.4128, lng: -1.5143,
    nearestStation: "Hungerford",
    tags: ["hocktide", "tutti-men", "hungerford", "folk", "custom", "medieval", "berkshire", "civic"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Follow the Tutti-men on their door-to-door rounds; the Town Hall balcony for the horn-blowing and orange-throwing",
    lensSuggestion: "35mm or 50mm for doorstep encounters; 85mm for portraits of the Tutti-men in top hats with their flower poles",
    bestArrivalTime: "8:45am at the Town Hall for the horn blowing that starts the day",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    ritualSignificance: true,
    crowdSizeEstimate: "~500",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/af/HUNGERFORD_HOCKTIDE%2C_Hungerford%2C_Berkshire.jpg",
  },

  {
    slug: "garland-day-castleton-2026",
    title: "Garland Day, Castleton",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Derbyshire",
    city: "Castleton",
    description: "Every Oak Apple Day (29 May), the Garland King rides through Castleton on horseback with a vast beehive-shaped garland of spring flowers covering his entire upper body and head. Only his face is visible through the blooms. The queen flower at the top is hoisted to the church tower pinnacle at the end of the procession — where it remains until it withers.",
    startDate: d(5, 29),
    allDay: false,
    startTime: "18:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 53.3440, lng: -1.7780,
    nearestStation: "Hope (Sheffield–Manchester line)",
    tags: ["garland", "oak apple day", "castleton", "derbyshire", "custom", "horse", "flowers", "peak district"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The main street for the king on horseback surrounded by flowers; the churchyard for the garland hoisting finale",
    lensSuggestion: "85mm for the garland king portrait; 50mm for the procession through the stone-built village streets",
    bestArrivalTime: "5:30pm to secure a spot before the procession starts at 6pm",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    crowdSizeEstimate: "~1,000–2,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/78/GarlandKing%26Consort.jpg",
  },

  {
    slug: "bawming-the-thorn-2026",
    title: "Bawming the Thorn, Appleton Thorn",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "North West",
    county: "Cheshire",
    city: "Appleton Thorn",
    description: "Children dance around the ancient hawthorn tree on the village green, decorating it with ribbons, garlands, and flags in a ceremony believed to stem from a cutting of the Holy Thorn of Glastonbury. 'Bawming' is an old dialect word for adorning. One of England's most intimate and charming surviving tree customs.",
    startDate: d(7, 4),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 53.3671, lng: -2.5588,
    nearestStation: "Warrington Bank Quay",
    tags: ["hawthorn", "bawming", "tree", "children", "folk", "cheshire", "custom", "ribbons"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "The village green — it is an intimate event in a small space, easily accessible from all sides",
    lensSuggestion: "50mm or 85mm for the children and the decorated tree; 35mm for the full scene",
    bestArrivalTime: "1:30pm for the gathering and preparations before the ceremony",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    crowdSizeEstimate: "~300–500",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/New_Village_Sign_Appleton_Thorn_-_geograph.org.uk_-_1613175.jpg",
  },

  {
    slug: "rushbearing-grasmere-2026",
    title: "Rushbearing, Grasmere",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "North West",
    county: "Cumbria",
    city: "Grasmere",
    description: "In Wordsworth's village, children carry elaborate rush-and-flower bearings to St Oswald's Church — a survival of the medieval practice of covering church floors with rushes. The bearings are ornate works of art woven from rushes and decorated with flowers into crosses, harps, and shields. Carried in procession through the village with hymns and a brass band.",
    startDate: d(7, 25),
    allDay: false,
    startTime: "11:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.4596, lng: -3.0237,
    nearestStation: "Windermere (then bus 555)",
    tags: ["rushbearing", "grasmere", "wordsworth", "lake district", "flowers", "custom", "church", "children"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "The village procession for the children carrying the rush bearings; the churchyard for the display and blessing",
    lensSuggestion: "50mm for the procession; 85mm for portraits of children with their intricate rush bearings",
    bestArrivalTime: "10:30am to see the bearings assembled before the procession departs",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    crowdSizeEstimate: "~1,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Frank_Bramley_%281857-1915%29_-_The_Grasmere_Rushbearing_-_419408_-_National_Trust.jpg",
  },

  {
    slug: "well-dressing-tissington-2026",
    title: "Well Dressing, Tissington",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Derbyshire",
    city: "Tissington",
    description: "Tissington is the oldest well dressing village in England. On Ascension Day, five wells are dressed with intricate biblical pictures made entirely from flower petals, mosses, seeds, berries, and natural materials pressed into wet clay boards. A craft unique to Derbyshire, taking weeks to prepare. The displays remain for a week in this exceptionally picturesque estate village.",
    startDate: d(5, 14),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 53.0714, lng: -1.7410,
    nearestStation: "Uttoxeter (then car)",
    tags: ["well dressing", "tissington", "derbyshire", "flowers", "peak district", "craft", "custom", "ascension"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Each of the five wells — all within easy walking distance through the village",
    lensSuggestion: "90mm macro for detail of the petal mosaic work; 24–35mm for the well in its village context",
    bestArrivalTime: "Morning on Ascension Day for the blessing service and fewest visitors",
    daytimeNightValue: "daytime",
    ritualSignificance: true,
    crowdSizeEstimate: "~2,000–5,000 over the week",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Well_Dressing_Tissington_Derbyshire_UK_2007.jpg",
  },

  {
    slug: "egremont-crab-fair-2026",
    title: "Egremont Crab Fair & World Gurning Championship",
    type: "FAIR",
    status: "SCHEDULED",
    region: "North West",
    county: "Cumbria",
    city: "Egremont",
    description: "One of England's oldest fairs (established 1267). Crab apples are thrown from a moving cart to the crowd. Events include greasy pole climbing, hound trailing, and pipe smoking. The undisputed highlight is the World Gurning Championship — competitors pull the most grotesque face possible through a horse collar (the braffin). Extraordinary close-up portrait opportunity unlike anything else.",
    startDate: d(9, 19),
    allDay: false,
    startTime: "10:00",
    endTime: "21:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.4828, lng: -3.5283,
    nearestStation: "Whitehaven (then bus)",
    tags: ["gurning", "world championship", "fair", "crab apples", "cumbria", "eccentric", "face pulling", "medieval"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The gurning stage for face portraits — get as close as possible; the street for the crab apple cart chaos",
    lensSuggestion: "85mm or 135mm for the gurning competitors — compression and subject isolation are key",
    bestArrivalTime: "Morning for the fair atmosphere; the gurning championship runs from late afternoon into the evening",
    daytimeNightValue: "both",
    ritualSignificance: true,
    crowdSizeEstimate: "~5,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Wonderferret_gurns_%28cropped%29.jpg",
  },

  {
    slug: "world-conker-championships-2026",
    title: "World Conker Championships",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East Midlands",
    county: "Northamptonshire",
    city: "Southwick",
    venueName: "Southwick village",
    description: "Every second Sunday of October, hundreds of competitors from around the world converge on the tiny village of Southwick. Conkers on strings, safety goggles, fierce concentration, and comic pratfalls — all in aid of charity. The ultimate celebration of British eccentricity, in an autumnal setting of horse chestnuts and village greens.",
    startDate: d(10, 11),
    allDay: true,
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.4312, lng: -0.4237,
    nearestStation: "Peterborough (then car)",
    tags: ["conkers", "world championship", "eccentric", "autumn", "northamptonshire", "british", "village"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "Ringside at the conker fights for concentration faces and the swing moment; village green for crowd atmosphere",
    lensSuggestion: "85mm for action shots of the conker swing — the action is fast; 50mm for the crowd",
    bestArrivalTime: "Morning for registration and the early rounds",
    daytimeNightValue: "daytime",
    ritualSignificance: true,
    crowdSizeEstimate: "~3,000",
    officialUrl: "https://www.worldconkerchampionships.com/",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/The_Conker_Round_-_geograph.org.uk_-_767891.jpg",
  },

  {
    slug: "allendale-baal-fire-2026",
    title: "Allendale Baal Fire",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "North East",
    county: "Northumberland",
    city: "Allendale Town",
    description: "At midnight on New Year's Eve, 'guisers' in fancy dress carry blazing half-barrels of tar on their heads through the streets of Allendale Town before hurling them onto a vast bonfire in the market place. One of England's oldest and most spectacular fire ceremonies. The bonfire is lit to burn out the old year and welcome the new one.",
    startDate: d(12, 31),
    allDay: false,
    startTime: "23:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.8966, lng: -2.2522,
    nearestStation: "Hexham (then taxi/car)",
    tags: ["fire", "new year", "baal fire", "northumberland", "guisers", "tar barrels", "night", "ceremony"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The market place for the procession arrival and bonfire; street level for close-ups of barrel carriers with fire overhead",
    lensSuggestion: "f/2.8 or wider, ISO 3200–6400, 35mm prime. Fire is the primary light source — expose for the flames not the crowd",
    bestArrivalTime: "11pm to secure a market place position before it fills completely",
    daytimeNightValue: "night",
    fireSmokeLight: true,
    ritualSignificance: true,
    costumeCeremonial: true,
    routeMoving: true,
    safetyNotes: "Burning tar barrels are carried directly overhead through the crowd. Stand back and protect camera from ember fall.",
    crowdSizeEstimate: "~2,000–3,000",
  },

  {
    slug: "carhampton-wassailing-2026",
    title: "Carhampton Apple Wassailing",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South West",
    county: "Somerset",
    city: "Carhampton",
    description: "Every Old Twelfth Night (17 January), the oldest known wassailing ceremony in England. Villagers process to the oldest apple tree in the orchard by torchlight, toast it with cider, fire shotguns through the branches to drive away evil spirits, and sing the wassailing song. Toast soaked in cider is hung in the branches to feed the robins — guardians of the tree. An extraordinary, fire-lit winter ceremony.",
    startDate: d(1, 17),
    allDay: false,
    startTime: "19:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.1810, lng: -3.4500,
    nearestStation: "Taunton (then car)",
    tags: ["wassailing", "apple", "carhampton", "somerset", "torchlight", "cider", "folk", "custom", "winter"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The orchard itself — the torchlit procession and fire around the tree is best experienced at close range",
    lensSuggestion: "f/2.8, ISO 3200–6400, 35mm prime. Firelight and torches are the only illumination — embrace the grain",
    bestArrivalTime: "6:30pm for the torchlit procession to the orchard",
    daytimeNightValue: "night",
    fireSmokeLight: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    safetyNotes: "Shotguns are fired through the tree branches at close range — ear protection recommended.",
    crowdSizeEstimate: "~200–400",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Shirehampton_wassail_music.jpg",
  },

  {
    slug: "goathland-plough-stots-2026",
    title: "Goathland Plough Stots",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "Yorkshire",
    county: "North Yorkshire",
    city: "Goathland",
    description: "On Plough Monday (first Monday after Epiphany), the Goathland Plough Stots perform their ancient long-sword dance through the village. Eight dancers in traditional costume perform an intricate interlocking sword figure — unique to the north of England. One of the few continuous living traditions of Plough Monday sword dancing, performed in the village that inspired the TV series Heartbeat.",
    startDate: d(1, 12),
    allDay: false,
    startTime: "10:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 54.4015, lng: -0.7388,
    nearestStation: "Whitby (then car/bus); or North Yorkshire Moors Railway to Goathland station",
    tags: ["plough monday", "sword dance", "goathland", "yorkshire", "folk", "custom", "moors", "long sword"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The village green and pub forecourt for the sword dances; follow the side through the village for intimate doorstep performances",
    lensSuggestion: "35mm or 50mm for the sword figures; 85mm for portraits of the dancers in costume",
    bestArrivalTime: "9:45am at the village green for the first performance",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    crowdSizeEstimate: "~200–500",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Goathland1.jpg",
  },

  {
    slug: "tichborne-dole-2026",
    title: "Tichborne Dole",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "Hampshire",
    city: "Tichborne",
    description: "Every Lady Day (25 March), the Tichborne family distributes flour to every local person who claims it under an 800-year-old deathbed promise. Lady Mabella Tichborne, dying in 1150, begged her husband to provide for the poor. He agreed to give them the yield of whatever land she could crawl around while a brand burned. She circled 23 acres. The dole has been paid ever since — interrupted only once, when the family was cursed.",
    startDate: d(3, 25),
    allDay: false,
    startTime: "14:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.0716, lng: -1.2228,
    nearestStation: "Alresford",
    tags: ["tichborne", "dole", "lady day", "hampshire", "custom", "medieval", "flour", "charity"],
    featured: true,
    photoScore: 4,
    bestViewingPosition: "The house forecourt for the blessing and distribution; the queue of claimants stretching through the village",
    lensSuggestion: "50mm or 85mm for portraits of the Tichborne family and the flour recipients",
    bestArrivalTime: "1:30pm to see the preparations and the gathering crowd of claimants",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    ritualSignificance: true,
    crowdSizeEstimate: "~200–400",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Tichborne_dole.jpg",
  },

  {
    slug: "oxford-may-morning-2026",
    title: "Oxford May Morning",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "Oxfordshire",
    city: "Oxford",
    venueName: "Magdalen Bridge / Magdalen College",
    description: "At 6am on May Day, the Magdalen College choir sings a Latin hymn from the top of the Great Tower — a tradition since 1501. Thousands gather on Magdalen Bridge below. Morris dancers perform on the bridge and throughout the city streets, maypoles are raised, and Oxford celebrates the arrival of summer. The bridge used to be closed until 2012 when students jumped into the Cherwell; it is now a controlled but euphoric celebration.",
    startDate: d(5, 1),
    allDay: false,
    startTime: "06:00",
    endTime: "10:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.5222, lng: -1.2469,
    nearestStation: "Oxford",
    routeDescription: "Magdalen Bridge for the tower singing; morris dancing spreads through High Street and surrounding colleges",
    tags: ["may morning", "oxford", "magdalen", "choir", "morris dancing", "may day", "tower", "tradition"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Magdalen Bridge for the crowd and tower shot; High Street for the morris dancers at dawn; the bridge itself for the choir singing overhead",
    lensSuggestion: "24–70mm for the bridge crowd against the tower; 85mm or 200mm to isolate the choir high on the tower; 35mm for the morris dancers",
    bestArrivalTime: "5:30am to secure a position on or near the bridge before crowds make it impossible",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    previousYearNotes: "The pre-dawn atmosphere on the bridge is extraordinary — thousands gathered in silence as the first notes come from the tower. Dawn light by 6am in May.",
    crowdSizeEstimate: "~10,000–15,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/80/Magdalen-may-morning-2007-panorama.jpg",
  },

  {
    slug: "ickwell-may-day-2026",
    title: "Ickwell May Day",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "East of England",
    county: "Bedfordshire",
    city: "Ickwell",
    description: "One of the most traditional May Day celebrations in England, held on the village green at Ickwell since the 17th century. A May Queen is crowned, maypole dances are performed by the village schoolchildren, and the green fills with morris dancers, a fair, and villagers in traditional dress. The permanent maypole at Ickwell is one of the tallest in England.",
    startDate: d(5, 4),
    allDay: false,
    startTime: "13:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 52.0867, lng: -0.3548,
    nearestStation: "Biggleswade",
    tags: ["may day", "maypole", "may queen", "ickwell", "bedfordshire", "village green", "children", "folk"],
    featured: false,
    photoScore: 4,
    bestViewingPosition: "The village green — the maypole is permanent and central; position for the ribbon weaving dances",
    lensSuggestion: "50mm for the maypole weaving; 85mm for the May Queen ceremony portraits",
    bestArrivalTime: "12:30pm for the May Queen procession before the maypole dancing",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    bannersFlagsCandles: true,
    crowdSizeEstimate: "~1,000–2,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Maypole_dancing%2C_Ickwell_Green%2C_Bedfordshire_-_geograph.org.uk_-_3445844_%28cropped%29.jpg",
  },

  {
    slug: "bampton-morris-dancing-2026",
    title: "Bampton Traditional Morris Dancing",
    type: "CUSTOM",
    status: "SCHEDULED",
    region: "South East",
    county: "Oxfordshire",
    city: "Bampton",
    description: "Bampton has the longest continuous tradition of Morris dancing in England — unbroken since at least the 18th century. Every Whit Saturday, the Bampton Traditional Morris Men dance through the village, visiting pubs and private houses, accompanied by a fool, a cake-bearer, and a musician. The white costumes with ribbons and bells, and the ancient figures danced in the narrow Oxfordshire streets, are exactly what Morris dancing looked like centuries ago.",
    startDate: d(5, 23),
    allDay: false,
    startTime: "10:00",
    endTime: "18:00",
    recurringAnnual: true,
    free: true,
    indoorOutdoor: "OUTDOOR",
    lat: 51.7246, lng: -1.5455,
    nearestStation: "Oxford (then car)",
    tags: ["morris dancing", "bampton", "oxfordshire", "whitsun", "folk", "custom", "traditional", "bells"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "Follow the side through the village — doorstep performances are intimate and accessible; the pub garden sets are lively",
    lensSuggestion: "35mm or 50mm prime for the dancing in tight village streets; 85mm for the fool and individual dancer portraits",
    bestArrivalTime: "10am to join from the first set and follow the side through the day",
    daytimeNightValue: "daytime",
    costumeCeremonial: true,
    processionElements: true,
    ritualSignificance: true,
    routeMoving: true,
    bannersFlagsCandles: true,
    previousYearNotes: "The fool's antics between dances are as photogenic as the dancing itself. Follow closely — the side moves constantly through the village.",
    crowdSizeEstimate: "~500–1,000",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/Mosaic_of_Morris_Dancers_etc%2C_Market_Square%2C_Bampton%2C_Oxon_-_geograph.org.uk_-_7966459.jpg",
  },

  {
    slug: "sidmouth-folk-week-2026",
    title: "Sidmouth Folk Week",
    type: "FESTIVAL",
    status: "SCHEDULED",
    region: "South West",
    county: "Devon",
    city: "Sidmouth",
    description: "One of the world's great folk festivals, held on the seafront of this Regency seaside town every first week of August since 1955. International dance troupes, English ceilidh bands, Appalachian dancers, African drumming, and Catalan groups have all appeared. Performances spill onto the beach, the prom, and in pub sessions throughout the town. The combination of extraordinary folk performance and a beautiful Victorian seaside setting makes it outstanding for documentary photography.",
    startDate: d(8, 7),
    endDate: d(8, 14),
    allDay: true,
    recurringAnnual: true,
    free: false,
    indoorOutdoor: "BOTH",
    lat: 50.6808, lng: -3.2388,
    nearestStation: "Exeter St Davids (then bus or taxi)",
    tags: ["folk festival", "sidmouth", "devon", "international dance", "ceilidh", "morris", "seafront", "world music"],
    featured: true,
    photoScore: 5,
    bestViewingPosition: "The Ham (seafront arena) for the main international displays; the Esplanade for spontaneous street dancing; pub sessions at the Marine and the Swan for intimate folk music",
    lensSuggestion: "35mm or 50mm prime for the seafront and pub sessions; 85–200mm for the arena stages with international groups",
    bestArrivalTime: "Daytime for arena performances; late evening for the pub sessions and spontaneous dancing on the prom",
    daytimeNightValue: "both",
    costumeCeremonial: true,
    processionElements: true,
    bannersFlagsCandles: true,
    routeMoving: true,
    previousYearNotes: "The free outdoor performances on the seafront are as good as the ticketed arena. International groups often dance spontaneously on the prom between sets.",
    officialUrl: "https://sidmouthfolkweek.co.uk/",
    crowdSizeEstimate: "~70,000 over the week",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pecs%C3%A6tan_Morris_Sidmouth_Folk_Festival_2023.jpg",
  },
];

async function main() {
  console.log(`Seeding ${events.length} extra events…`);

  for (const e of events) {
    const evt = await prisma.event.upsert({
      where: { slug: e.slug },
      update: {
        officialUrl: e.officialUrl ?? null,
        // Only overwrite imageUrl if the seed explicitly provides one — preserve manually-added images
        ...(e.imageUrl !== undefined && { imageUrl: e.imageUrl }),
      },
      create: {
        slug: e.slug,
        title: e.title,
        type: e.type,
        status: e.status,
        region: e.region,
        county: e.county ?? null,
        city: e.city ?? null,
        venueName: e.venueName ?? null,
        description: e.description,
        startDate: e.startDate,
        endDate: e.endDate ?? null,
        startTime: e.startTime ?? null,
        endTime: e.endTime ?? null,
        allDay: e.allDay,
        recurringAnnual: e.recurringAnnual,
        free: e.free ?? null,
        indoorOutdoor: e.indoorOutdoor ?? null,
        lat: e.lat ?? null,
        lng: e.lng ?? null,
        routeDescription: e.routeDescription ?? null,
        nearestStation: e.nearestStation ?? null,
        travelNotes: e.travelNotes ?? null,
        tags: e.tags,
        featured: e.featured,
        officialUrl: e.officialUrl ?? null,
        imageUrl: e.imageUrl ?? null,
        archived: false,
        photoMeta: {
          create: {
            photoPotentialScore: e.photoScore,
            bestViewingPosition: e.bestViewingPosition ?? null,
            lensSuggestion: e.lensSuggestion ?? null,
            bestArrivalTime: e.bestArrivalTime ?? null,
            daytimeNightValue: e.daytimeNightValue ?? null,
            costumeCeremonial: e.costumeCeremonial ?? false,
            fireSmokeLight: e.fireSmokeLight ?? false,
            bannersFlagsCandles: e.bannersFlagsCandles ?? false,
            processionElements: e.processionElements ?? false,
            ritualSignificance: e.ritualSignificance ?? false,
            protestVisibility: e.protestVisibility ?? false,
            routeMoving: e.routeMoving ?? false,
            safetyNotes: e.safetyNotes ?? null,
            previousYearNotes: e.previousYearNotes ?? null,
            crowdSizeEstimate: e.crowdSizeEstimate ?? null,
          },
        },
        sources: {
          create: {
            sourceType: SourceType.MANUAL,
            notes: "Manually curated",
          },
        },
      },
    });

    // Update crowdSizeEstimate on existing photoMeta records
    if (e.crowdSizeEstimate) {
      await prisma.photoMeta.updateMany({
        where: { eventId: evt.id },
        data: { crowdSizeEstimate: e.crowdSizeEstimate },
      });
    }
  }

  console.log("Done.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
